MQTT_BROKER = "192.168.99.6"
MQTT_PORT = 1883

HTTP_HOST = "0.0.0.0"
HTTP_PORT = 5000

TOPIC_VISION = "room/vision/person"
TOPIC_MOTION = "room/motion"
TOPIC_DOOR = "room/door"
TOPIC_ALARM = "room/alarm"
TOPIC_MODE = "room/fusion/mode"

CAMERA_SOURCE = 0
FRAME_W = 640
FRAME_H = 480

MODEL_WEIGHTS = "yolov5n.pt"
DEEPSORT_CKPT = "ckpt.t7"

DET_CONF_THRES = 0.5
DET_IOU_THRES = 0.5
PERSON_CLASS_ID = 0

MIN_STABLE_FRAMES = 3
TRACK_TTL_SEC = 1.5
PUBLISH_INTERVAL_SEC = 1.0
FRAME_SLEEP_SEC = 0.01
